### ISSUE TITLE
Time interval for evaluating fleet size increases

### ISSUE THREAD

**Issue by sleibman** [CityOfLosAngeles/mobility-data-specification#11]
We suggest that LADOT consider a regular time interval to evaluate increases in fleet size by a dockless company. Quarterly revisions makes sense to us. We suggest the following revised rules for Fleet Size rules E, F, and G:

> e) All Operators are limited to a fleet-size of 500 Vehicles at launch. If a company wishes to deploy a combination of Vehicles (whether bikes, e-bikes, or scooters), the total number of vehicles that each company can launch cannot exceed a total of 500 Vehicles.

> f) Operators will be allowed to increase the size of their fleets by 250 vehicles per quarter after reviewing bike placement plans with city officials and receiving approval. 

> g) The overall fleet size per Operator may not exceed 1,500 Vehicles.

**Comment by LADOTBikeshare** [comment]
Thank you for your comments. The comments have been reviewed and taken into consideration. This issue is now closed.
