### ISSUE TITLE
Redundant "type" fields in route definition

### ISSUE THREAD

**Issue by cttengsfmta** [CityOfLosAngeles/mobility-data-specification#112]
The example route definition is

```js
"route": {
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "properties": {
            "timestamp": 1529968782.421409
        },
        "geometry": {
            "type": "Point",
            "coordinates": [
                -118.46710503101347,
                33.9909333514159
            ]
        }
    },
    {
        "type": "Feature",
        "properties": {
            "timestamp": 1531007628.3774529
        },
        "geometry": {
            "type": "Point",
            "coordinates": [
                -118.464851975441,
                33.990366257735
            ]
        }
    }]
}
```

The `"type": "FeatureCollection"` field is redundant. Routes are always collections of features. They can't be anything else. Similarly `"type": "Feature"` is redundant. An object is a list called "features" is a feature by definition.

**Comment by thekaveman** [comment]
This is a little verbose yes, but it follows the [GeoJSON format](http://geojson.org/) for geographic data types in JSON, specifically [Feature](https://tools.ietf.org/html/rfc7946#section-3.2) and [FeatureCollection](https://tools.ietf.org/html/rfc7946#section-3.3) There is a fairly large body of work around GeoJSON that we get to take advantage of by formatting the data in this way (libraries is many languages, online tools/validators/visualizers, etc.)

**Comment by hunterowens** [comment]
@cttengsfmta I would like to keep as aligned as possible to GeoJSON format, so I'm gonna close this issue for now. Please let me know if you have any other questions.
