### ISSUE TITLE
[Agency] Can a unique_id be reused after deregister ?

### ISSUE THREAD

**Issue by HenriJ** [CityOfLosAngeles/mobility-data-specification#115]
It would be best for simplicity and "auditability" purposes to not be able to reuse a unique_id even if deregistered. If so, maybe it should be mentioned in the specification ?
The difference between the error codes 305 (already registered) and 311 (duplicate registration) is also not completely clear ?

**Comment by toddapetersen** [comment]
A unique `device_id` may only be used once to create a vehicle.  However, you may send a `register` event after a `deregister` event, to (re)register the same vehicle.  Error codes have been updated as well.

**Comment by toddapetersen** [comment]
@hunterowens clarified in #224.  Please merge and close this if you agree.
https://github.com/CityOfLosAngeles/mobility-data-specification/blob/initial-event-state-fix/agency/README.md#vehicle-events

**Comment by hunterowens** [comment]
Thanks! merged.
