### ISSUE TITLE
update JSON Schema to handle optional fields

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#128]
Running list of JSON validator fixes 

* Currently, the parking_verification_field in trips is required, not optional, causing my validator to fail. 
* Change `0.{version_number}.{anynumber}` regex for `version` to `{anynumber}.{anynumber}.{anynumber}-{anystring_or_null}` to more close match semvar

**Comment by ian-r-rose** [comment]
On the second point: I agree that the last field should be `{anynumber}-{anystring-or-null}`. However, I think the first two should be kept the same: if an instance with major version `0.1.0` tries to validate against a schema of version `0.2.0`, then it should fail based on the version number alone. My understanding of semver is that, pre-1.0, every minor version is effectively a major version.

**Comment by thekaveman** [comment]
I think the major concern @hunterowens raises with point two is, having to update that regex every time there is a new point release is one more thing to remember to do. And it would be a bad thing to forget.

**Comment by hunterowens** [comment]
Additional thing to fix is that `actual_cost` and `real_cost` are optional, but current fail if null.

**Comment by ian-r-rose** [comment]
Should `accuracy`, `trip_duration`, and `trip_distance` be integers? My ontological sense thinks they should be floating point numbers, but there may be some context that I am not aware of.

**Comment by thekaveman** [comment]
@hunterowens:

> Currently, the parking_verification_field in trips is required, not optional, causing my validator to fail.

That field is not in the list of [required properties in the Trips schema](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/provider/trips.json#L232):

```json
 "trips": {
    "$id": "#/properties/data/properties/trips",
    "type": "array",
    "title": "The Trips Schema",
    "items": {
        "$id": "#/properties/data/properties/trips/items",
        "type": "object",
        "title": "The Trip Schema",
        "required": [
            "provider_name",
            "provider_id",
            "device_id",
            "vehicle_id",
            "vehicle_type",
            "propulsion_type",
            "trip_id",
            "trip_duration",
            "trip_distance",
            "route",
            "accuracy",
            "start_time",
            "end_time"
        ],
    }
}
```

However that property does have a [validation regex pattern](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/provider/trips.json#L350) that forces `HTTPS`, is that maybe the issue?

```json
"parking_verification_url": {
    "$id": "#/properties/data/properties/trips/items/properties/parking_verification_url",
    "type": "string",
    "description": "A URL to a photo (or other evidence) of proper vehicle parking",
    "default": "",
    "examples": [
        "https://data.provider.co/parking_verify/1234.jpg"
    ],
    "pattern": "^(https://.*)$"
}
```

**Comment by thekaveman** [comment]
Ok, that makes sense then. I think [this SO post](https://stackoverflow.com/questions/16241333/specify-a-value-can-be-a-string-or-null-with-json-schema#16241482) has a way to update the schema to handle null. I'll get that in a branch and we can try.

**Comment by ian-r-rose** [comment]
@thekaveman I think your proposed solution looks good to me. Unless you want the `parking_verification_url` to be non-nullable :) Some people have very strong opinions about `null` values.

**Comment by thekaveman** [comment]
It sounds like we're already seeing it in the wild right @hunterowens? So do we allow data like you pasted above, or should the spec say "optional fields must not be included when they do not have a value"?

**Comment by thekaveman** [comment]
I submitted a PR with the fix to allow `null` values. I can easily back that out if we don't want to, and re-word the README language to be clearer per my suggestion above.

There is another fix in that PR related to the Schema, and I targeted a new branch `0.2.x` I just cut from `dev` for non-breaking changes for the next patch release.

**Comment by hunterowens** [comment]
Yep.

**Comment by thekaveman** [comment]
@hunterowens Question about the `links` property for API paging: I'm seeing data like

```json
{
    "links":
    {
        "next": "https://....",
        "prev": null,
        "first": null,
        "last": null
    }
}
```

For the purposes of paging, this is really all we need... but it doesn't pass schema validation. I think we should probably allow an additional exception like in #142 for these `links` properties (only `next` would be required). Thoughts?
