### ISSUE TITLE
Write up Release procedure

### ISSUE THREAD

**Issue by thekaveman** [CityOfLosAngeles/mobility-data-specification#129]
There are manual and automated steps that must happen for each release.

In the interest of keeping everyone in the loop and making sure others can release if needed, a short document describing the release process would be beneficial.

**Comment by dyakovlev** [comment]
A release checklist would be awesome. Related to that, some sort of published guidance on how MDS semver is intended to work would be helpful. (I'm looking to get an idea of answers to questions like, when are releases cut? when are versions deprecated? how is implementation of new versions required? is there a version negotiation process at request time? at some other time?)

**Comment by hunterowens** [comment]
Shipped!
