### ISSUE TITLE
GBFS Data Pagination

### ISSUE THREAD

**Issue by f3d0r** [CityOfLosAngeles/mobility-data-specification#149]
It appears Bird's GBFS feeds available [here](https://mds.bird.co/gbfs/) are all limited to 100 bikes per response. Changing the `page` query appears to change the response of the data, but different "pages" have overlapping results for bikes, and there is no limit to the max and min pages (even negative page queries will return results). Is there a way to receive all real-time data in one request, or at least get the valid pages for receiving real-time data for all mobility vehicles? Is the pagination for GBFS similar to what they have described [here](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/ecebf75140a0c47e06299098e89afe4c1d16b393/provider/README.md#general-information)?

**Comment by thekaveman** [comment]
See the earlier discussion on this topic in #145. In summary, pagination of GBFS data is outside the scope of MDS for right now, as this should really be decided by that community. 

There was a related issued opened over on NABSA/GBFS#112
