### ISSUE TITLE
Add Unique ID for Availability Periods 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#15]
in the provider API

**Comment by dmklinger** [comment]
committed but unable to push

**Comment by hunterowens** [comment]
@dmklinger can you open a  pull request on a separate branch for review.

**Comment by hunterowens** [comment]
See [this documentation from github](https://help.github.com/articles/creating-a-pull-request/)

**Comment by hunterowens** [comment]
Closed in #17
