### ISSUE TITLE
Participate in and/or align with efforts in MaaS Alliance?

### ISSUE THREAD

**Issue by brylie** [CityOfLosAngeles/mobility-data-specification#151]
As you may know, the MaaS Alliance is an industry consortium who are working to promote harmonization and development of the MaaS ecosystem. Our technical working group members are assembling a set of [MaaS APIs](https://github.com/maas-alliance/apis), similar to this one, in an effort to promote interoperability.

Please consider joining the MaaS Alliance, participating in our technical working group, and/or simply collaborating with our members. This will promote harmonization across continents, since we are really working towards the same vision. :-)

**Comment by hunterowens** [comment]
Hi @brylie! Sorry for the delay in responding, but feel free to reach out to ladot.innovation@lacity.org. There is also the new [Open Mobility Foundation](https://www.openmobilityfoundation.org/)
