### ISSUE TITLE
add 'support_versions' endpoint

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#152]
To each API, add a supported version for programmatic checking of supported versions. Related to #147

**Comment by hunterowens** [comment]
How to articulate this, IMO. 

MDS, as a spec, supports 2 minor versions. (ie, 0.2 and 0.1 rn)

Cities, as part of their regulatory guidance, can *_require_* particular version #s. For example, SM may require latest while LA requires latest or latest -1.

Finally, implementations, of either provider _or_ agency, support n versions. For example, `company_x`’s Provider implementation might support 0.1.1, 0.2.0 and 0.3.1 while  LA’s agency implementation might support 0.3.0

**Comment by oderby** [comment]
@hunterowens after writing up #216, I'm not sure I see the reason/value in this. Can you elaborate on what solving this would enable?
