### ISSUE TITLE
Add license_url as top level provider property

### ISSUE THREAD

**Issue by asadowns** [CityOfLosAngeles/mobility-data-specification#163]
Similar to GBFS [System Information](https://github.com/NABSA/gbfs/blob/master/gbfs.md#system_informationjson) allow a `license_url`.

> A fully qualified URL of a page that defines the license terms for the GBFS data for this system, as well as any other license terms the system would like to define (including the use of corporate trademarks, etc)

While providers can provide this anyways as the response payload is defined as only the minimal payload, it would be good to call this out explicitly so providers know where they should provide this information and so agencies are aware of these terms for compliance purposes.

**Comment by thekaveman** [comment]
Off-topic but important clarification:

> ...the response payload is defined as only the minimal payload

This is **definitively not the case**. [`additionalProperties: false`](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/0.2.x/provider/trips.json#L388) in various parts of the schema disallows any but the defined properties.

**Comment by black-tea** [comment]
Confirming comments by @thekaveman: a top-level property `license_url` would in fact be in violation of MDS. This may change at some point in the future, but I am now closing this issue.

**Comment by asadowns** [comment]
@black-tea can we please re-open this issue and/or create an issue to specifically address defining terms of use for MDS data. 

As mentioned this is a feature of GBFS and is an important requirement for providers given the lack of clarity some cities have provided about how they may use and release MDS data that is either Personally Identifiable Information when combined with other data in the cities' possession or may provide a competitive advantage if released to a competitor.

This is an important collaborative conversation to have between agencies and providers. Ideally, we could come up with a license that was acceptable to both agencies and providers. In addition to the other agencies I would like to hear @noonhub and @babldev thoughts here.

**Comment by babldev** [comment]
@asadowns @black-tea @thekaveman I'd be in favor of an equivalent system info endpoint that include some additional metadata.

It could include optional fields such as:
- License URL
- Supported rideable types (electric bike, electric scooter)
- Starting timestamp of operation
- Preferred time interval for requests to allow caching of API responses

**Comment by thekaveman** [comment]
> I'd be in favor of an equivalent system info endpoint that includes some additional metadata.

This is certainly an interesting idea, and sounds like a good issue to open for discussion. It sounds related to some of these conversations we've been having in #152 and #171.

Specifically regarding the license URL, I will just put this out there from a city/agency perspective: it is nearly guaranteed that there does not exist a single license from the provider side that all agencies would be able to agree to. 

My feeling is, a license has to be a discussion between each agency/provider, and should not be a part of MDS. As we have already seen with some providers choosing to surreptitiously include a license in their data, the mere presence of a license URL does not in itself hold any weight. The much more important piece is the *agreement*, which by its very nature has to be a conversation / offline decision.

**Comment by babldev** [comment]
> it is nearly guaranteed that there does not exist a single license from the provider side that all agencies would be able to agree to.

I agree that MDS should be the medium for agency <-> provider communication, and not specify the data sharing license itself.

**Comment by asadowns** [comment]
@thekaveman @babldev I see your points on having a license be something that is specified based on discussion between each agency/provider. That being said, I still think there's value in having a: 

_`license_url` that explicitly does not reference city usage but licenses all other usage?_

Does that seem more reasonable?

In regards to a system information endpoint I think that makes a lot of sense. I'll create another issue so we can discuss that item separately but I think having a place to list rate limits and/or  preferred polling frequency and some other metadata makes a lot of sense.
