### ISSUE TITLE
Support microtransit vehicle types and metadata

### ISSUE THREAD

**Issue by FordSmartMobility** [CityOfLosAngeles/mobility-data-specification#167]
Currently, the `vehicle_type` field present in the Provider spec supports only `bicycle` and `scooter` values.  Consider expanding the types available to include values such as `sedan`, `suv`, `minivan`, and `van`; if the direction is to keep things a bit more generic, these types could be classified under a single `automobile` category.

Further, the following fields could be added as supplemental information for microtransit types:

- `capacity`: The number of seats bookable to the public (e.g. not including the driver)
- `occupancy`: The number of people/seats booked in a trip
- `wheelchair_accessibility`: True/false

These fields could be available as part of a collection of trips, i.e. `Journey`, that describes a driver's shift.  Trips could then roll up or be otherwise associated to a journey.

**Comment by hunterowens** [comment]
@FordSmartMobility Thanks for the suggestion! We're working on figuring out how to support multiple vehicle types, see #95. 

My preference is that we use the code in `generate_schema` to use common datatypes (such as `Point`, `timestamp`, etc) and then each mobility type gets a subfolder in both `agency/` and `provider/`. 

This would 1) make the JSON schema more robust and 2) make it easier to adapt the spec for more mobility options as they happen.

**Comment by FordSmartMobility** [comment]
Great!  We'll close this issue in favor of continuing the conversation through the issue referenced above.
