### ISSUE TITLE
Determine how to support multiple modes

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#170]
ref #95 #167 #157. 

We need to figure out structurally how to support different modes aside from bikes/scooters.

**Comment by HenriJ** [comment]
@hunterowens do you already have a list of the different modes that should be supported ?

* Bikes/scooters = station-based (we might require an API to register stations like we have an API for areas ?) or dockless with no information on trip destination
* Car-sharing = station-based or free-floating. Trip destination can sometimes be known but not always
* TNC (& taxis ?) = confidentiality issues as reported by #95 . We should always know the trip destination.

Attributes of the vehicles are different for each mode but the macro-structure of the API should stay the same ?

**Comment by d-wasserman** [comment]
I think one overarching aspect that might change is an aspect related to occupancy if possible for other modes. Thinking of services like Via or TNC's pooled services, I could see that being a useful attribute. Currently, the macro-api (correct me if I am wrong) assumes a single trip corresponds to a single person. Down the line, I could see something like this interacting with a tolling APIs, etc.

**Comment by hunterowens** [comment]
moving to `0.4.0`, as I don't have a great answer for this yet but would like to get the 0.3.0 changes out the door.

**Comment by hunterowens** [comment]
closed in #366!
