### ISSUE TITLE
Document what type of Auth can be in each endpoint

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#171]
Currently, `provider/auth.md` doesn't show what endpoints can be covered with what types of limits / auth. 

*Proposal:*

`provider/auth.md` show that GBFS endpoints should be open to the public, while `/trips/` and `/status_changes` can be restricted to a municipality. 

For open to the public, there is a question of allowing companies to rate limit queries to that endpoint.

**Comment by black-tea** [comment]
I like this suggestion.

**Comment by hunterowens** [comment]
I think NABSA is fairly clear that GBFS should be made open, IIRC.
