### ISSUE TITLE
Define expected ordering

### ISSUE THREAD

**Issue by ezheidtmann** [CityOfLosAngeles/mobility-data-specification#189]
As I read it, the current provider spec does not specify an ordering and does not provide a mechanism for providers to expose the ordering method they are using. 

If the spec defined an expected ordering and providers match the spec, polling can be more efficient.

**Comment by thekaveman** [comment]
While you were the first to raise this issue @ezheidtmann, the conversation really took off on #191, #272, #273, #301 (and maybe others I'm missing). Closing just to clean things up.
