### ISSUE TITLE
Support for modification of entities is not clear

### ISSUE THREAD

**Issue by ezheidtmann** [CityOfLosAngeles/mobility-data-specification#190]
Providers are currently free to modify entities after first publication but there is not a mechanism for communicating a modification date or querying for entities modified after a certain time.

The spec should either explicitly disallow modification after publication, or provide suitable support for modification dates.

**Comment by ezheidtmann** [comment]
Discussion of entity modification also happening in #192

**Comment by hunterowens** [comment]
@ezheidtmann we've added `publication_time` as part of `0.3.2`, let's test how once providers implement that if it also us to detect modifications. If there are any other changes you'd like to see as 0.4.0, LMK.
