### ISSUE TITLE
Publication date is not exposed or queryable

### ISSUE THREAD

**Issue by ezheidtmann** [CityOfLosAngeles/mobility-data-specification#192]
Presumably the `event_time` or `end_time` closely precedes the publication date, but the spec doesn't require any specific behavior here and doesn't expose this date. Consumers thus have to make assumptions about when trips or status changes are expected to become available.

For example, can a consumer expect that if a trip ending at 11:00 am is published, then no trips ending before that time will be published later? Probably not; things happen out-of-order all the time.

I'd suggest adding a publication & modification date to the spec, and allowing consumers to query based on one or both of those keys.

**Comment by asadowns** [comment]
It's worth noting the provider API specifies that the endpoints available are for _historical_ data. In our case we handle this by only returning data one minute prior to the current time which ensures all data is up to date and setting that timestamp as the "last" available on API calls.

#163 currently involves a discussion around adding a `system_information` type endpoint where I think it makes sense to include a timestamp for latest available data, or some similar representation. Modification is a trickier. I would suggest simply that providers provide a timestamp representing their rough adoption date of the version of the specification returned.

In regards to the question of order, I can't think of a situation where events would be processed out of order but it certainly depends on the specific provider implementation.

**Comment by ezheidtmann** [comment]
Cool, thanks for that info on your implementation, that's very helpful for consumers! Do you ever modify trip objects after publication? For example, if `actual_cost` changes due to support activity, would that be reflected in the provider API?

The Santa Monica and LA consumer implementations both work by polling, and they appear to assume that modification never occurs. I'm hoping to verify whether providers share this assumption, and if so, add it to the spec.

**Comment by hunterowens** [comment]
`publication_time` was included in the 0.3.2 release~!
