### ISSUE TITLE
Timestamp in Agency

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#199]
Per @HenriJ

`Could we add a timestamp field the event so that if we receive it later, we can know the real time when it occurred ?

**Comment by hunterowens** [comment]
@CityOfLosAngeles/ellis-associates can you document how to pass time in the past in a request to  an Agency API server? The use case @henrij and I are trying to document is a recursive trip_start call, but that may be gone now that we are hard bounding `trip_start` and `trip_leave`.

**Comment by toddapetersen** [comment]
Latest version of Agency includes a timestamp associated with every event and telemetry point.
