### ISSUE TITLE
Pagination Query Parameters

### ISSUE THREAD

**Issue by niketanpatel** [CityOfLosAngeles/mobility-data-specification#200]
i initially had some confusion about how providers should go about paginating their APIs and how clients should consume from the MDS paginated apis. this was all written out here and clarified by @thekaveman https://github.com/CityofSantaMonica/mds-provider/pull/57

so if clients shouldn't have to understand the query parameter schema in the `next` url of the `links` body, then the provider APIs should be able to use a stateless pagination token in the query parameter so they know when to send a response with an empty `next` url

this pagination token would be created upon the first request the client makes, and added onto the query parameters of the `next` url in the response (ie. `?start_time=100&end_time=199&page_token=...`. this will make it so that every subsequent request made by the client using the `next` url will have the information for what time window the client requested, so that the server can know when to return `next` url as `null`.

so since provider APIs are meant to implement pagination however they want, if they were to use query parameters in this manner, **is there a way that we can reserve and document query parameter keywords for pagination?** i would want to avoid the case where some provider API uses the query parameter `page_token` and then in the future, for whatever reason, we require the parameter `page_token` to be used for some other purpose.

@thekaveman @hunterowens thoughts?

**Comment by oderby** [comment]
The [JSON API specification](https://jsonapi.org/format/1.0/#fetching-pagination) linked from MDS is pretty clear on this point:
> The `page` query parameter is reserved for pagination. Servers and clients SHOULD use this key for pagination operations.

Is there something more than that you're looking for in this specification?

**Comment by thekaveman** [comment]
I think deferring to JSON API is appropriate. I don't think MDS is interested in reserving keywords for something that is a provider implementation detail.

**Comment by niketanpatel** [comment]
ah, that sounds good!
