### ISSUE TITLE
MDS Governance

### ISSUE THREAD

**Issue by asadowns** [CityOfLosAngeles/mobility-data-specification#206]
Improving MDS governance will make it the standard for cities looking to consume mobility data and encourage an ecosystem of data ingestion, analytics, and monitoring tools. By ensuring a stable and inclusive governance structure for MDS, cities other than Los Angeles will adopt it, knowing that their concerns will be addressed and they will have a voice in the process.

I truly believe MDS will flourish in 2019 through the `0.3.0` release and beyond but a more inclusive approach to governance will make that road much easier.

MDS as it currently stands is under the sole ownership of the City of Los Angeles with input from the City of Santa Monica. In order to drive adoption of MDS by other agencies and properly capture the concerns of providers, MDS ought to set up a governance structure that addresses the interests of these different stakeholders. This could be modeled on existing standard bodies such as the W3C.

Whenever there is a single entity governing a specification that is broadly used across multiple entities, it risks creating a fractured landscape due to the inability for stakeholders to democratically contribute to improvements and the development of competing specifications. This would be bad for cities as it would mean less development, thought, and tooling going into MDS and the ghettoization of mobility device reporting.

**Comment by hunterowens** [comment]
closing because the [Open Mobility Foundation](https://www.openmobilityfoundation.org/) is now a thing.
