### ISSUE TITLE
[agency] Merge update_trip_telemetry into /event ?

### ISSUE THREAD

**Issue by sebdiem** [CityOfLosAngeles/mobility-data-specification#207]
I would suggest merging the `update_trip_telemetry` endpoint defined in [1] into the `vehicles/{id}/event` endpoint.
This could be done by adding a new `trip_telemetry` vehicle event.
In addition the required body parameter `telemetry` in the `vehicles/{id}/event` endpoint is not specified in the spec. It's probably also worth merging with the `Route` type (a `Route` is simply an ordered list of telemetries).

What do you think about this ?

[1] https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/agency#update_trip_telemetry

**Comment by sebdiem** [comment]
Ok, I saw the discussions on https://github.com/CityOfLosAngeles/mobility-data-specification/pull/194 .
Maybe it is indeed relevant to keep 2 separate endpoints that could be scaled differently (the telemetry endpoint is expected to receive more load obviously).
However to keep things "restish" I would rename `vehicles/{id}/update_telemetry` to `vehicles/{id}/telemetry`

**Comment by karcass** [comment]
The PR is to change telemetry submission to `/vehicles/telemetry`.  Because telemetry is expected to be > 99% of the transactions, telemetry is batched and not per-vehicle.

**Comment by sebdiem** [comment]
Oh yes indeed submission to `/vehicles/telemetry/` is addressed in https://github.com/CityOfLosAngeles/mobility-data-specification/pull/196/ .
Thanks.
