### ISSUE TITLE
LADOT MDS Compliance Questions

### ISSUE THREAD

**Issue by asadowns** [CityOfLosAngeles/mobility-data-specification#208]
After evaluating LADOT’s application, we have the following outstanding questions:

* What are the City's expectations for the maintenance schedule and logs? How often is it expected that we update this information? What is the report-maintenance API? Is this the Agency API?
* Can you publicly provide a detailed methodology for how you plan on evaluating caps?
* What should we be preparing for in terms of an implementation of the Agency-side API? What is the timeframe?
* Requirement to comply with MDS-agency within 30 days of final is onerous for any company. This conflicts directly with MDS’ documentation which specifies ongoing support for previous minor release in this case `0.2.1`. We propose a 90-day grace period after the specification is released. Would LADOT be amenable to that?
* How will the city be evaluating compliance within the parking standard?
* How do we best certify compliance with `0.3.0` when it has not yet been released? How long do we have to come into compliance after it is released?
* How can we get access to the city's program portal to update our organizational chart and contact information?

**Comment by toddapetersen** [comment]
We will address all of these questions during the MDS Agency webinars on 2/7/19.  Please reopen individual issues, if you feel they were not addressed.
