### ISSUE TITLE
Provider Route Precision

### ISSUE THREAD

**Issue by asadowns** [CityOfLosAngeles/mobility-data-specification#209]
The Provider `README.md` states

> routes must include all possible GPS samples collected by a provider.

and the example route points include coordinates such as `33.9909333514159` with 13 degrees of precision. 

In practice, rounding to 5-6 decimal places is already at the limit of GPS accuracy and useful precision with the remainder of the decimals being noise. 

Is it acceptable for providers to round number of decimals to 5 or 6 places. This would reduce payload and storage size for route data substantially.

**Comment by hunterowens** [comment]
@asadowns introduce a PR to allow this in #223

**Comment by karcass** [comment]
The reference implementation of `agency` truncates to 6 decimal places
