### ISSUE TITLE
Clarification on service_start and service_end

### ISSUE THREAD

**Issue by dbaty** [CityOfLosAngeles/mobility-data-specification#211]
The spec says (both in agency and provider parts) that `service_start` and `service_end` event type reasons are to be used when the "device [is] introduced into service at the beginning of the day (if program does not operate 24/7)" (respectively when the "device [is] removed from street because service has ended for the day (if program does not operate 24/7)").

Can these reasons be used also when the device enters the service for the very first time and when it permanently leaves the service? I am asking especially in the case of a service that do operate 24/7, but it would be as useful for services that don't.

If so, I would suggest adapting the description of these reasons in the specification. Something like:

> A device is introduced into service either for the very first time or, for programs that do not operate 24/7, at the beginning of the day.

> A device is removed from street either permanently or because service has ended for the day (if program does not operate 24/7).

If we cannot use these reasons, perhaps there is a need for additional event type reasons? I am not sure about the naming: maybe `operation_start` and `operation_end`?

Depending on the direction, I will gladly prepare a pull request.

**Comment by karcass** [comment]
The event for (semi-)permanently-leaves-service is `deregister` and it puts the device in the `inactive` state.  Of course it can be re-registered.  This is how you distinguish daily operations from lifecycle operations.

**Comment by dbaty** [comment]
Unfortunately, these `register` and `deregister` event types are defined only in the *agency* part of the API: https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/agency#vehicle-events. They are not included in the list of event types and event type reasons in the provider part of the API (for the `status_change` endpoint): https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/provider#event-types. It is my understanding that we should have a single list of all events for both parts of the API.

**Comment by karcass** [comment]
Yep, they should eventually be the same list.   Hopefully they'll get lined up by 0.3, but if not, Provider can just ignore them for now.  `user_pick_up` and `trip_start` are the same thing and should be considered equivalent, as well.  I'll check with @hunterowens to see if he's amenable to reconciling them this week.

**Comment by hunterowens** [comment]
@dbaty @karcass 

I think this might be an area where provider and agency diverge. `agency` has the register/deregister context in the active management of the entire fleet and universe, while provider uses `status_change` to track when something has entered or exited the PROW. 

I think it would be appropriate for a device to have a `service_start` event for the first event, although I am unsure if there would be a corresponding `service_end` event. @dbaty can you let me know what removals from the PROW are not being currently covered by the spec.

In #77, there is discussion of how to refactor `event_type_reason`. Let's consolidate this discussion over there, I'm going to close this issue for now.
