### ISSUE TITLE
[AGENCY] 5 minute telemetry requirement

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#212]
Currently, agency requires that provides report telemetry every 5 minutes. Given the nature of these devices, that may not be truthful data when it is reported. We might want to have a different reporting requirement. @whereissean

**Comment by toddapetersen** [comment]
What I believe we are really after is ~100ft (30 meter) reporting when the device is in motion and a watchdog timed report if the vehicle is deployed.   Using 100 ft and 30 minute watchdog, here is a suggestion in pseudo code

if (vehicle_status == 'reserved' || vehicle_status== 'trip')   // according to Vehicle Events table
        report_type = 'distance';
        report_distance = 100; //ft
else
        report_type = 'time';
        report_time = 30;   //minutes

**Comment by karcass** [comment]
Five _seconds_, not five _minutes_.

**Comment by karcass** [comment]
I would be interested in hearing the current GPS rates the providers are using internally.  The goal is to keep data accurate and fresh, not impose dramatic new bandwidth demands on the devices.

**Comment by jsierles** [comment]
I'm also interested to understand what the actual requirement will be for compliance, now that it seems a one year permit may only be applied for once Agency API compliance is met.

**Comment by jsierles** [comment]
OK, thanks for the update. Is the documentation available already for those who cannot attend the webinar?

**Comment by karcass** [comment]
I believe it will be available Monday.
