### ISSUE TITLE
Backporting trips end-time-based filtering from v 0.3 to 0.2.2

### ISSUE THREAD

**Issue by krithin** [CityOfLosAngeles/mobility-data-specification#213]
@babldev contributed https://github.com/CityOfLosAngeles/mobility-data-specification/pull/139, which greatly simplifies filtering `/trips` by time. 

I agree with @oderby's comment on that PR that removing the `start_time` and `end_time` query parameters and replacing them with `min_end_time` and `max_end_time` would be a breaking change that should be deferred to MDS version 0.3. Until that arrives, however, this is going to continue to be a problem that will affect any sort of periodic MDS provider data ingestion pipeline.

Would it be possible to backport just adding those filters (without worrying about removing `start_time` or moving from floating-point seconds timestamps to integer milliseconds) to the next point release (v 0.2.2)? If that's a possibility I can prepare a PR for it.

If MDS v 0.3 is going to be released soon this might not be necessary.

**Comment by hyperknot** [comment]
This can also be just the decision of the providers. For example, [as reported](url
https://github.com/CityOfLosAngeles/mobility-data-specification/pull/139#issuecomment-447030168) Lyft is already using end_time filters.

**Comment by asadowns** [comment]
fwiw Bird is doing this as well.

**Comment by krithin** [comment]
@hyperknot I don't think calling it "just the decision of the providers" is a great idea.

If multiple providers are ignoring the (unintuitive) spec as written and are instead implementing the more easy-to-use behavior that will become the default in 0.3, that's all the more reason to explicitly add in 0.3-style time filtering in the spec now rather than letting MDS and the providers' implementations of it diverge.

**Comment by hyperknot** [comment]
@krithin you mean doing a 0.2.2 with 0.3.0 style time filtering? If so, I agree, this should be done.

**Comment by hunterowens** [comment]
Given that we're shooting to close out `0.3.0` soon, I'm going to close this issue.
