### ISSUE TITLE
Add company name to status change

### ISSUE THREAD

**Issue by dmklinger** [CityOfLosAngeles/mobility-data-specification#22]
also swap ordering of device id and device type. then it's consistently big endian: company > device types > specific device

**Comment by hunterowens** [comment]
Shouldn't we know the company name based on what API endpoint is being queried?

**Comment by dmklinger** [comment]
We will have to add a company field to the sql table (unless you want to keep different tables for different companies, which we probably do not), and it is easier to just pull it from them than to manually keep track of the company we are querying and add it.

**Comment by thekaveman** [comment]
I agree with @dmklinger here, this would be a useful field to have as part of the data coming down from the API. Although we will know the company, IMHO it is worth some duplication for the added flexibility and scalability of that information being encoded in the data itself.

Imagine a future where there are hundreds of companies operating - it would be great to be able to query the `/provider` APIs "blindly", where the code doesn't *have* to know which individual provider it is hitting.

This would also be consistent with the [gbfs `system_information.name`](https://github.com/NABSA/gbfs/blob/master/gbfs.md#system_informationjson) field.

**Comment by hunterowens** [comment]
This seems reasonable. {and consistent with GBFS, which we aim to
supplement) Let's do PR for it on Thursday.
