### ISSUE TITLE
Expected output of agency /vehicles endpoint when no device_id is specified is unclear

### ISSUE THREAD

**Issue by johnpena** [CityOfLosAngeles/mobility-data-specification#242]
The [documentation](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/agency#vehicles) for the agency API's `/vehicles` endpoint specifies that the `device_id` parameter is optional and that "If provided, retrieve the specified vehicle". What is the expected output if `device_id` is not provided? The documentation should specify the expected outcome when `device_id` is not provided given that it's optional. 

I would expect that either a) the endpoint should return a list of all registered vehicles when no `device_id` is provided b) the endpoint should return an error code, and the documentation should be changed to specify that `device_id` is required.

**Comment by karcass** [comment]
Ah yeah, sorry about that.  We never reached consensus as to whether or not `GET /vehicles` should behave as your (a) or (b).  Not sure that it matters as long as we pick one.  I think we should get the opinion of a few folks representing providers to express a preference one way or the other.

**Comment by karcass** [comment]
What do you think @johnpena?

**Comment by johnpena** [comment]
I'd prefer option (a) as it'll give providers transparency into the fleet data the agency has on hand, and to audit/correct issues as needed.

**Comment by karcass** [comment]
Sounds legit.  I figured that's what most folks would prefer.  I'll write up a PR.

**Comment by johnpena** [comment]
Thanks for looking into this!
