### ISSUE TITLE
Remove UUID4 validation for device_id and trip_id in agency api

### ISSUE THREAD

**Issue by amalakar** [CityOfLosAngeles/mobility-data-specification#244]
In the current specification the api mandates that the following fields are UUID4 (as per https://github.com/CityOfLosAngeles/mobility-data-specification/tree/1b0fb7ba707d85d0cfbc8cb5d4bd2ae90fd351e1/agency )

| Field | Type | Required/Optional | Comments |
|---|---|---|---|
| device_id | UUID4 | Required | ID used in Register |
| trip_id |	UUID4 |	Required	| UUID provided by Operator to uniquely identify the trip. |

This breaks backward compatibility though, the provider api didn't require these fields to be UUID4, and it needed it just to be an UUID as per: https://github.com/CityOfLosAngeles/mobility-data-specification/tree/1b0fb7ba707d85d0cfbc8cb5d4bd2ae90fd351e1/provider

| Field | Type | Required/Optional | Comments |
|---|---|---|---|
| device_id | UUID | Required | A unique device ID in UUID format |
| trip_id |	UUID |	Required	| A unique ID for each trip |

In our system lot of the above fields are in uuid v1 which would fail to validate as UUID4 (because the version number 4 is not present in the uuid), this stops us from ingesting those device_id using the agency api. The agency api throws `not a valid UUID4`, would you please consider removing the validation of UUID4 and let it be just an UUID to match the provider api.

**Comment by karcass** [comment]
Opened PR to downgrade Agency to validate UUID only.  Sandbox is updated as of now (Friday 2/22 9A PST).  Will close this after PR is merged.

**Comment by amalakar** [comment]
Thank you @karcass for the prompt response, appreciate the collaboration.
