### ISSUE TITLE
Agency: relax telemetry requirements

### ISSUE THREAD

**Issue by lionel-panhaleux** [CityOfLosAngeles/mobility-data-specification#246]
On the Agency API, many fields are _required_ for telemetry but depending on the onboard device and third party software, the information may not be available:
- altitude
- heading
- speed
- HDOP
- number of satellites

Could they be optional instead ?
PR attached : https://github.com/CityOfLosAngeles/mobility-data-specification/pull/245

**Comment by dirkdk** [comment]
Thanks! The onboard computers that we currently use at Spin do not send out heading and speed, so very much appreciated.

**Comment by oderby** [comment]
@karcass now that #245 has merged, we can close this, right?

**Comment by hunterowens** [comment]
Fixed in #261 #245 I believe.
