### ISSUE TITLE
Agency API suggests vehicle events can be refused

### ISSUE THREAD

**Issue by lionel-panhaleux** [CityOfLosAngeles/mobility-data-specification#248]
I believe this should not be the case because:

- Events order is hard to guarantee for the provider
- Agency API should not be blocking for providers
- No specific finite-state machine should be imposed

Also from the Agency point of view, computing the state of a device by using the last event, without assuming anything on the business workflow of the provider, seems like the most stable route.

Attached PR: https://github.com/CityOfLosAngeles/mobility-data-specification/pull/247

**Comment by karcass** [comment]
See #250

**Comment by lionel-panhaleux** [comment]
Thanks, added some commits to #250

**Comment by hunterowens** [comment]
closing because #250 and #247 are merged.
