### ISSUE TITLE
Group Agency API into Categories

### ISSUE THREAD

**Issue by toddapetersen** [CityOfLosAngeles/mobility-data-specification#25]
Need to decide what endpoints are going to be active in Version 1.0 (Jan)

**Comment by toddapetersen** [comment]
@hunterowens  How would you like this to show up in the Git?  Currently we're using the head (#) for end-points on both the provider and agency side.   How should we format categories?    Rather than changing the format everywhere, it may make more sense to remove the future API's from the master until after it's tagged.    Thoughts?

**Comment by thekaveman** [comment]
In a software project, a typical git/branching structure is: 

- the `master` branch represents the currently-deployed "live" code. 
- another branch (sometimes called `dev`) represents work on the *next* version.
- when it comes time to release the next version, `dev` is merged into `master` and a tag is created to mark the release.

That could also work here... `master` contains the initial (*provider*) spec at release, and `dev` could contain work on the *agency* spec (or some part of it). Feature branches off of `dev` could be used for individual portions of the *agency* spec (e.g. `agency-register-vehicle`), and merged into `dev` when they are "ready".

**Comment by toddapetersen** [comment]
@thekaveman  Agreed.

**Comment by thekaveman** [comment]
@toddapetersen @hunterowens regarding the idea *remove the future APIs from `master` until after its tagged*:

I think for the purposes of launching our pilots, this is a good idea. I'm prepping a PR for some `provider` cleanups ahead of the pilot, I can also include the removal of the `agency` spec in the PR...thoughts?

**Comment by thekaveman** [comment]
See #40 - I'm happy to fold in the *remove the future APIs* idea if that is something LADOT is interested in.

**Comment by hunterowens** [comment]
This probably should have happened, sorry for my misinterpretation earlier this week. Anyways, closing. 

I think the 0.2.0 release should be the first release where agency is functional, we might want to remove it from 0.1.1 when I get that out the door.
