### ISSUE TITLE
Agency: allow accuracy as well

### ISSUE THREAD

**Issue by ezheidtmann** [CityOfLosAngeles/mobility-data-specification#260]
Some software configurations don't provide an HDOP figure, but do provide an accuracy measurement in meters. For example, both iOS and Android platforms do this. At least one operator has Android running on the vehicle, and at least one operator has used the user's smartphone to collect some GPS data.

Rather than asking operators to back out HDOP in these situations, the spec should support receiving a "radius of accuracy in meters."

**Comment by karcass** [comment]
Seems legit.  I'll add that.  PR forthcoming.

**Comment by hunterowens** [comment]
fixed in #360
