### ISSUE TITLE
Refine release process / cadence 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#262]
Currently, `ReleaseGuidlines.md` dictates the main release process for MDS. Notably, it doesn't commit to any particular release timeline, and only really address "how" to make a release once it is ready, not "what makes a release candidate". 

It is also unclear who exactly will be reviewing any given PRs, and given the constraints on my time, PRs / issues don't get the attention and/or care they deserve. 

There are number of issues that a refined release process could help, and moving to both a regular schedule and defined comment period could really help. 

Additionally, we have no `CONTRIBUTING.md`, although there is a proposed one in #170. We should make it clear on how to contribute and what will happen once you make a PR or Issue, or would like to comment outside of github. 

I'd like to do a number of things to improve the release process will help with the questions raised in #206.

**Comment by jfh01** [comment]
Minor correction to above: proposal for CONTRIBUTING.md is in #176.

**Comment by hunterowens** [comment]
With #264 merged, closing this for now.
