### ISSUE TITLE
Add external_case_id to /status_changes endpoint for linking MDS and 311 data

### ISSUE THREAD

**Issue by jfh01** [CityOfLosAngeles/mobility-data-specification#269]
One of the use cases for `provider` is to help cities monitor compliance with requirements around issue response. For example, if a city reports an misparked vehicle or other safety issue to a provider, the city will want to know if/when the issue was resolved.

Eventually, there will be a larger project to create all the hooks to facilitate full integration between city 311/issue tracking systems and mobility providers. But as a short-term step, would propose adding an optional `external_case_id` field to the `/status_changes` endpoint. This would allow for simple data linkages between 311 systems and provider issue management workflow.

For example, a city reports a problem to a provider (digitally or manually) and includes a case id for the related 311 issue. As the provider moves through its own workflow to resolve the issue, the 311 case id could continue to be tracked. When the provider makes a vehicle status change is made related to that case (such as relocating the misparked vehicle), the 311 case id would be provided back to the city via the `external_case_id` field on the `/status_changes` endpoint.

I'd welcome perspectives on the relative value of creating a lightweight integration hook now versus just waiting until we can properly design a full set of integrations that allow for more seamless digital workflows between 311 systems and mobility providers.

**Comment by toddapetersen** [comment]
Hi Jascha,

I have not thought about this deeply yet, but on first blush, it seems like an unnatural way to use a data ingestion API.   Should we not think about instead using a trip_ID and/or device_ID (depending on the nature of the 311 incident) to link the trip to a resolution?    Seems more natural for issue status to persist with the 311 system then with provider.    

If you are trying to create a way to sync between 311 systems and a data aggregator, then we can probably do that through a purpose built API.

**Comment by jfh01** [comment]
Based on my experience w/ 311 reporting in Boston, I'm guessing many requests won't come in with a device ID (especially those called in). I think we'll need a way to link a record about a vehicle status change to a 311 request after the request is submitted to the provider.

The workflow I'm imagining is:

1. Constituent reports issue in 311
2. City notifies provider with a location
3. Provider visits location and relocates/removes vehicle
4. Provider notifies city of resolution

At the moment, all of this would happen out-of-band of MDS and there would not necessarily be a way to link MDS records back to the work that was done to verify that the vehicle was in fact moved within an allowed time window.

It may make sense to keep all of this out-of-band and use a separate API for syncing. It does seem like we'd want to build it off the existing MDS data structure though so there's a clear data linkage between vehicle status changes in MDS and issues reported in 311.

**Comment by hunterowens** [comment]
Theoretically, the what should happen at step 3 is either. 

1) There is no device / no illegal parking / no issue, no `status_change` is generated, but ticket is closed in the 311 system. 
2) There is a device, corresponding `status_change` event should be generated. I'm in favor of adding an optional `associated_ticket` or similar for the status change. 

Given that the device may remain on the curb, we may need other status change events to support this.
