### ISSUE TITLE
Create standard way to designate intended milestone and API in issue subjects

### ISSUE THREAD

**Issue by jfh01** [CityOfLosAngeles/mobility-data-specification#270]
Because setting an issue/PR milestone and label requires write access to the repository, issues submitted by general contributors won't start with either milestone or label attached.

Suggest that we establish a standard designation in the issue title to indicate which version and which API an issue/PR is targeted for. 

Issues titles would be prefixed with `[version / API]`.

For example:

`[0.3.1 / agency]`
`[0.4.0 / provider]`
`[provider]` (for an issue/PR that does not yet have an intended version.

If folks agree with this approach, would need to update `CONTRIBUTING.md` and create issue templates for the repository that guide people to use the correct designation.

**Comment by hunterowens** [comment]
Perhaps we should just have people submit - something like 

```
[ ] Breaking 
[ ] Non-Breaking 
[ ] I'm unsure 

``` 

in each issue, allowing them to tag the info that the maintainers need for clarification into milestone + labels.

**Comment by jfh01** [comment]
Closing this issue to be worked on #286.
