### ISSUE TITLE
Event timestamp unicity

### ISSUE THREAD

**Issue by lionel-panhaleux** [CityOfLosAngeles/mobility-data-specification#272]
On a single device, different vehicle events (agency side) and status changes (provider side) should have different timestamps.

In the specification as it is, nothing prevents a provider to present multiple status changes on a single timestamp value for the same device. I guess this is not expected, as it makes the resulting vehicle status undecidable for the agency.

**Comment by thekaveman** [comment]
I think this is more or less the conversation that was started in #191, would you care to continue over there?

**Comment by lionel-panhaleux** [comment]
Thanks for the pointer, added a comment there.

**Comment by thekaveman** [comment]
Just cleaning up, since this conversation has evolved on #191, and a few open PRs.
