### ISSUE TITLE
Provider API: status changes order

### ISSUE THREAD

**Issue by lionel-panhaleux** [CityOfLosAngeles/mobility-data-specification#276]
Hello,

Following discussions with @karcass on using the sandbox API, we agreed the status changes should be ordered chronologically.

They are most likely seen as a time series, but as it is not precisely specified, providers could very well paginate the results in any order they see fit. The API would be easier to use if a stable order is specified.

I'll attach a PR with a proposition for a basic `event_time` increasing order, but we could introduce a full order on the (`event_time`, `device_id`) pair: this will be required anyway for proper pagination on the provider side, and if https://github.com/CityOfLosAngeles/mobility-data-specification/issues/272 get through, this pair in particular would make sense.

What do you think ? Thanks for your comments.

**Comment by thekaveman** [comment]
@lionel-panhaleux @karcass would you mind elaborating on some of those discussions? I can see reasons for doing this, even related to some points in #268; I'm curious of your thoughts. 

#277 makes a language change to the README, where the schema file is the more formal validating document - any thoughts on how this new requirement could be enforced?

Provider has been fairly stable on the "paging is an implementation detail" idea, this goes the other way... (not necessarily a bad thing, just context)

**Comment by lionel-panhaleux** [comment]
Well, I would agree that the exact pagination method used should stay an implementation detail - an internal ID for a cursor ? An encoded `timestamp:device` pair ? There are some options there, and depending on the technical stack, some are easier than others.

However, the chronological order gives some stability to any polling or analysis technique used  : the endpoint is there to be used by the agency, and the fact that it provides time filtering already hints that it is seen as some kind of a time series.

Getting the events without chronological order makes the data harder to treat on the agency side : until the last page is fetch, no way to know if an event is missing in the middle of the timeline. This instability makes it impossible to treat the data as a stream in a pipeline.

It relates to #268 in some aspects: if this is presented as a time series, making the API easier to use as a stream, it can help agencies use more stable queries. If the API is often called from start to end for a full polling operation, no caching technique can help, but some form of pre-fetch can be achieved. On the other hand, if most of the time only recent data is fetched for a refresh, it can be cached effectively in some way.

Even if it is not reflected in the schema, the ordering feels natural and would come in handy on the agency side because the assumption that events come in "in order" makes it easier to handle.

I was thinking putting it in the text part of the spec could be enough, but if it can be added in the schema, I'm all for it.

**Comment by karcass** [comment]
@thekaveman @lionel-panhaleux I am totally agnostic as to whether any more paging specificity in Provider is warranted.  The reference implementation of Provider-from-Agency currently uses skip/take paging because it's simple and flexible, but to provide consistent results ('stable queries') with this pagination, the ordering has to be chronological.

**Comment by hunterowens** [comment]
closing this as well, in favor of the #357
