### ISSUE TITLE
Clarify breaking vs non-breaking changes

### ISSUE THREAD

**Issue by ccolgrove** [CityOfLosAngeles/mobility-data-specification#279]
For the purposes of minor releases, we should only be releasing "non-breaking" changes. However, traditionally "non-breaking" only refers to API consumers. How should we handle changes that are "breaking" (i.e. require implementation work) for API implementers? How much implementation work is required before a change considered "breaking"? If the answer is zero, that severely limits the usefulness of minor releases, but at the same time it's important to consider how much implementation time certain changes will take and to not have major implementation requirements too often.

**Comment by jfh01** [comment]
I took a crack at explaining this in the issue/PR templates (#286). Feedback welcome.

**Comment by ccolgrove** [comment]
Based on @jfh01's initial version in #286  and some discussion on the 4/4 call, the working definition of a breaking change is currently if it requires changes from either API consumers or API implementers. Some examples of breaking changes:

- Removing API functionality
- Semantic changes to existing functionality
- Mandatory new functionality

I'm going to leave this issue open for a bit to see if there's more discussion on this topic, but we shouldn't block #286 on resolving this.

**Comment by morganherlocker** [comment]
Agree, this is super important to define. Related issue is committing to explicit [versioning](https://github.com/CityOfLosAngeles/mobility-data-specification/issues/288). [Semantic versioning](https://semver.org/) is one way to handle this in a way most people will be familiar with.

**Comment by ccolgrove** [comment]
@morganherlocker yeah agreed that explicit versioning is important. This project already uses semver - currently it’s in the 0.x.y phase so we’re following the standard convention of minor releases are allowed to be breaking and patch releases are non-breaking. This issue is mainly about clarifying what constitutes non-breaking when your API has many implementers as well as many consumers. We chatted about this briefly on the weekly call (notes [here](https://github.com/CityOfLosAngeles/mobility-data-specification/wiki/Web-conference-notes,-4.4.2019)) and the general consensus seemed to be that we should treat both directions as breaking. @rf- just put up a PR [here](https://github.com/CityOfLosAngeles/mobility-data-specification/pull/295) if you want to take a look at the results of that - would be interested to hear your take.
