### ISSUE TITLE
Consider adding "experimental" designation to parts of the spec

### ISSUE THREAD

**Issue by ccolgrove** [CityOfLosAngeles/mobility-data-specification#280]
It's pretty important to be able to iterate quickly on these APIs in order to figure out what works in practice, but it can be tough for organizations who have limited resources to keep up with fast-moving APIs. One potential solution is to designate new, untested parts of the spec as "experimental," with the expectation that these may break every release, or even be removed all together. Once the new feature has hardened, it can be moved into the "stable" part of the API, and will be expected to break much less frequently.

**Comment by morganherlocker** [comment]
Experimental features in the production spec adds significant instability. If a feature is not fully thought out and tested, it should not be in the current version of the spec at all. If there are unstable parts of the API, they should be removed from the spec until they are clearly defined. Hundreds of projects will be built following the specification, so if an idea is not ready yet, it needs to be tested in prerelease first, to avoid breaking the ecosystem. One reason is that an experimental change may contradict the stable parts of the spec, causing impossible to reconcile breakage.

**Comment by ccolgrove** [comment]
@morganherlocker  I definitely agree that testing new features before hardening them is super important. That’s the goal of this suggestion: allow a space for new, unstable features to be tested and refined before moving them into the stable part of the spec. Even if the goal is for one of these new features to eventually replace an existing feature, it could be implemented in an additive-only way at first, and then the switch could be made during a major version release.

But more broadly the problem to solve here is: MDS is still rapidly evolving. We don’t know all the use cases yet. How do you iterate quickly on parts of the spec (e.g. order of days) while still maintaining a predictable and relatively frequent release cadence for everything else? I’m not particularly tied to this solution, so I’d be interested to hear what alternatives you have in mind.

**Comment by hunterowens** [comment]
bump, @ccolgrove @morganherlocker, I'm facing this challenge with how to handle the `policy` endpoint.

**Comment by hunterowens** [comment]
closing this out for now.
