### ISSUE TITLE
Modify README.md to better reflect current state of project

### ISSUE THREAD

**Issue by jfh01** [CityOfLosAngeles/mobility-data-specification#287]
README.md is currently the home page for MDS (and the top Google result when searching for "mobility data specification"). But the page doesn't do a great job at capturing the current state and goals of the project, or showcasing involvement from cities other than LA.

Three proposed changes to README.md:

1) Add a paragraph to tell a little more about the origin story and values of MDS "Created by LADOT to be an open data standard, MDS is currently supported by multiple cities, mobility providers, and software companies. Participation in the project is open to all."

2) Replace the announcements (currently LA-focused) with a directory of links to city-specific micro-mobility pages. Any City that has adopted MDS would be allowed to provide a link to a page on their micromobility program and/or their use of MDS/data.

3) Modify Contact section to reference the MDS provider release process and point to relevant documents for details.

**Comment by hunterowens** [comment]
@jfh01 let me know if the changes in #332 covered this. Going to close for now, but feel free to reopen this one.
