### ISSUE TITLE
Add an associated trip id to status changes when a trip ends

### ISSUE THREAD

**Issue by billdirks** [CityOfLosAngeles/mobility-data-specification#289]
Currently the provider specification only requires an `associated_trip` for status change events if the `event_type_reason` is `user_pick_up` or `user_drop_off`. For trip starts an event with `event_type = reservation` and `event_type_reason = user_pick_up` appears mandatory. For trip ends, however, it seems possible that the vehicle doesn't become `available` (a scooter with low battery when a trip ends for example). In this example a trip would end with the state transition (`available`, `reserved`) to (`unavailable`, `low_battery`) and no `associated_trip` would be present in the status change event. It seems the intent is to have an `associated_trip` id present at end of trips even when there is no allowable `user_drop_off` `event_type_reason`.

**Comment by rf-** [comment]
It seems like a good idea to me to require an `associated_trip` for any status change that marks the beginning or end of a trip, regardless of the specific `event_type` and `event_type_reason` it represents. The spec is currently somewhat ambiguous about whether `associated_trip` is allowed for events that don't have a reason of `user_pick_up` or `user_drop_off`. I'd suggest the following language for 0.4.0:

> Trip UUID (foreign key to Trips API), required if `event_type_reason` is `user_pick_up` or `user_drop_off`, or for any other status change event that marks the end of a trip.

For 0.3.1, we could find a middle ground that explicitly allows providers to include the field for other event types but doesn't require it.

If and when the provider state machine is defined more clearly in a future version of MDS, I think it would make sense to allow edges going from the `reserved` state to `available`, `unavailable`, and potentially other statuses, with the stipulation that all edges going into or out of `reserved` should have an `associated_trip`.

**Comment by thekaveman** [comment]
The language of the spec was updated in #297 to be more explicit that `associated_trip` is allowed with any status_change event type. I think that closes this issue for now.
