### ISSUE TITLE
Reconcile changes made to Provider to Agency

### ISSUE THREAD

**Issue by toddapetersen** [CityOfLosAngeles/mobility-data-specification#29]
Hunter and David,  You guys mentioned in our last meeting that there were changes you made during implementation of the Provider side that need to be made to the Agency side.   Could you make those changes before we start building?

**Comment by hunterowens** [comment]
Tagging @dmklinger

**Comment by hunterowens** [comment]
@toddapetersen timeline you're looking for. 

I think the major changes off the top of my head are 

* the new `route` structure
* WGS:84 Compliance 
* anything else?

**Comment by toddapetersen** [comment]
I'd like to get it in by Tuesday next week.   Would also like to discuss some other changes we're considering to make the Agency side a little simpler for bikes.    I'll be in Monday if you have time to get together.

**Comment by hunterowens** [comment]
sounds good. I will take a stab at drafting today but let's meet on Monday to hash out.

**Comment by hunterowens** [comment]
I believe we actually only had to move stuff from Agency into Provider. Opened PR #34.
