### ISSUE TITLE
Inconsistencies between the Agency specification and the sandbox implementation

### ISSUE THREAD

**Issue by chennney** [CityOfLosAngeles/mobility-data-specification#292]
@hunterowens We're working with the agency sandbox and have encountered some inconsistencies with the spec or implementation:

1. The vehicle propulsion type of "electric_assist" is not considered a valid propulsion_type.
2. Within vehicle registration, the parameters for "year", "mfgr" and "model" are all marked as optional but the API requires it for registration.
3. The /vehicles endpoint returns the "year" parameter returns a String literal, but the spec states an Integer. The endpoint is also missing the device_id value for each vehicle record.
4. The /service_areas endpoint returns both Polygon and MultiPolygon, while the spec states MultiPolygon.

**Comment by karcass** [comment]
Hi @chennney, please use support@ladot.io for all questions about the implementation of agency.  I have forwarded this list of issues there.
