### ISSUE TITLE
Default MDS Provider version for client requests?

### ISSUE THREAD

**Issue by yoimnik** [CityOfLosAngeles/mobility-data-specification#306]
I'm wondering what should be the default MDS provider version used for client requests to provider APIs?

The spec for 0.3.x regarding versioning doesn't mention any version to default to if the client does not provide `Accept` headers.

For sake of a more smooth migration for clients, if they have code running somewhere that's hitting our APIs with requests that do not have `Accept` headers, we should continue to support that behavior -- which would be to give a 0.2.x response.

Thoughts?

**Comment by rf-** [comment]
The spec says:
> Since versioning was not added until the 0.3.0 release, if the Accept header is application/json or not set in the request, the provider API must respond as if version 0.2 was requested.

That behavior seems reasonable to me. I guess the implication would be that when providers eventually deprecate support for 0.2 then they'll reply with `406 Not Acceptable` to requests that don't include a valid `Accept` header.

**Comment by dyakovlev** [comment]
MDS is not really specific about what "must respond as if" implies regarding multiple concurrent version availability. From various discussions we've had about this, it seems that it is in the hands of Providers to decide if consumers of their APIs are relying on 0.2 to remain available and react accordingly.

In practice, as @rf- said, maintaining 0.2 responses as a fallback behavior is probably the most harmonious way forward in the short term.

**Comment by yoimnik** [comment]
Oh, oops -- thanks for quoting that @rf- 

Yeah, I agree with maintaining 0.2 responses as a fallback.

So in terms of any migration needed on any client code consuming from the API, all that's really needed is adding this `Accept` header and the adjusting the response fields (associated trips, timestamp, etc), correct?

Are there any other changes client code would have to make to the APIs for the new version?

**Comment by dyakovlev** [comment]
> So in terms of any migration needed on any client code consuming from the API, all that's really needed is adding this Accept header and the adjusting the response fields (associated trips, timestamp, etc), correct?

The request format for the `trips` endpoint was also changed to support querying by `min_end_time` and `max_end_time`.

**Comment by yoimnik** [comment]
Yes, that too :) Okay cool, just wanted to make sure I wasn't missing anything. Thanks all!

**Comment by dyakovlev** [comment]
No problem!

There's probably a couple more things worth looking at. The release notes were very useful to us when we did this update.

In particular, https://github.com/CityOfLosAngeles/mobility-data-specification/pull/226 formalizes some wording about event and trip visibility with respect to a city's municipal boundary.

**Comment by imthatcarlos** [comment]
On a related note, are we to accept minor versions as well?? I assumed not, since breaking changes wouldn't be introduced in these, however the spec for the minimal data in the response seems to include the minor version? Some clarification would be great! 

```
{
    "version": "x.y.z",
}
```

**Comment by dyakovlev** [comment]
since minor versions should be interoperable, I believe the intent was for the client to use the header to signal the major version only and for the server to have optionality of which minor version it responds with based on its internal implementation.

**Comment by imthatcarlos** [comment]
ahh yeah that makes sense as well! thanks @dyakovlev

**Comment by thekaveman** [comment]
I think this one was answered above! Please re-open if there are outstanding questions.
