### ISSUE TITLE
Provider API: Add a "recorded" field to status changes

### ISSUE THREAD

**Issue by lionel-panhaleux** [CityOfLosAngeles/mobility-data-specification#307]
### Is your feature request related to a problem? Please describe.

Polling status changes using the timestamp field is unreliable: an event can be recorded late, and ignored by the polling system if it uses the timestamp of the last polled event to fetch new ones.

### Describe the solution you'd like

Adding a `recorded` field in the status changes, and a query parameter in the `status_changes/` endpoint to query the events using this information.

### Is this a breaking change

* [x] Yes, breaking
* [ ] No, not breaking
* [ ] I'm not sure

### `Provider` or `agency`

For which API is this feature being requested:

* [x] `provider`
* [ ] `agency`
* [ ] both

### Describe alternatives you've considered

A global sequence ID seems less natural and would not convey the additional "time of recording" information.

### Additional context

The idea has been tested with our partners and is satisfactory. We would love to see it in MDS 0.4

**Comment by billdirks** [comment]
I don't understand what `recorded` is. What is its type and what values can it contain?

**Comment by lionel-panhaleux** [comment]
A better naming would be welcome :-) I was thinking a timestamp: the time when the event was recorded, ie. made available through the Provider API.

**Comment by billdirks** [comment]
Thanks for the clarification!

**Comment by dyakovlev** [comment]
some notes from the 5/9 call:

- suggestion was well received, mutual agreement that it addresses a problem experienced by many consumers
- alternative field wording: `publication_time` or `published_time` (to mirror `event_time`)
- this should be applied to the trips endpoint as well
- release-wise, this can be made optional in 0.3.x line but making it required would need to target 0.4.x

@lionel-panhaleux - sounds like this should move forward into a PR if possible!

**Comment by rf-** [comment]
That happened automatically because I referenced this issue in the PR, but y’all might want to reopen this issue to track making the field mandatory and adding the ability to query by it

**Comment by hunterowens** [comment]
I think maybe that is worth creating a new issue to track that under the `0.4.0` milestone
