### ISSUE TITLE
Timeliness of status change event data

### ISSUE THREAD

**Issue by billdirks** [CityOfLosAngeles/mobility-data-specification#315]
### Is your feature request related to a problem? Please describe.

Currently there is no requirement in the specification for the timeliness of status change data (or trip data). However, cities often turn to MDS to answer "real-time" questions like:

* How many scooters are available for rent right now?
* How many scooters are not working but still on the street right now?

### Describe the solution you'd like

One solution to this would be to require the status events be reported in a timely matter. For example, a provider should have a status event available for querying 5 minutes after the event occurs.

Another possible solution has been proposed in #310. It seems like they could be effective in unison.

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

* [ ] Yes, breaking
* [ ] No, not breaking
* [ X ] I'm not sure

It seems like a lot of implementors are currently timely with data since that is what cities expect. However, there is nothing explicit in the specification right now.

### `Provider` or `agency`

For which API is this feature being requested:

* [  X ] `provider`
* [ ] `agency`
* [ ] both

### Describe alternatives you've considered

#301

### Additional context

Some operators have indicated that they want to actively update status change events up to 24 hours (or longer) after it occurs. For example, at the weekly MDS meeting an operator stated they may want to run a machine learning algorithm over the raw data to make better predictions of location/state. This is not necessarily at odds with this suggestion if status change events are allowed to change after they are initially reported. Events do currently change (eg new events can be added, events can be deleted, etc) and this is not disallowed by the current specification.

**Comment by patata3000** [comment]
I'm 100% with you sir

**Comment by hunterowens** [comment]
I'm hoping that #357 is gonna help us make progress on this as an ecosystem, open to reopen if that isn't the case.
