### ISSUE TITLE
Error responses for invalid param for Provider API, same as Agency

### ISSUE THREAD

**Issue by dirkdk** [CityOfLosAngeles/mobility-data-specification#317]
We at Spin are supporting both MDS 0.2.0 and MDS 0.3.0 as provider API. We would like to help our users (= cities) to use the right requests with the right parameters. E.G. for `/trips`, `start_time` is a timestamp and this needs to be in milliseconds for 0.3.0. This was in seconds for 0.2.0. For this we would like to return errors with a clear description. Provider API currently has no specification how to return errors. `bbox` is not supported anymore for 0.3.0

### Adopt same error responses as for Agency API
The Agency part of the API already has error responses define: https://github.com/CityOfLosAngeles/mobility-data-specification/blob/dev/agency/README.md#responses

We propose to adopt the same structure for Provider.

### Is this a breaking change

* [ ] Yes, breaking
* [x] No, not breaking
* [ ] I'm not sure

### `Provider` or `agency`

* [x] `provider`
* [ ] `agency`
* [ ] both

### Describe alternatives you've considered

Alternative to return our own homegrown responses, that is not good

**Comment by hunterowens** [comment]
I think standardizing (or at least standardizing with some variation) the possible error codes should make implementing provider clients significantly easier, thanks for the suggestion @dirkdk

**Comment by karcass** [comment]
I support this 😄

**Comment by karcass** [comment]
In fact I will make a PR proposal for the Provider spec and see if it gets buy-in for 0.4.0.

**Comment by hunterowens** [comment]
fixed in #368
