### ISSUE TITLE
Update period for Trips not specified

### ISSUE THREAD

**Issue by toddapetersen** [CityOfLosAngeles/mobility-data-specification#33]
@hunterowens.  Apologies if I'm missing something, but I don't see where we are specifying the required update period for Trip data in the Provider API.    The Agency side arbitrarily mentions 5 seconds.   Any thoughts around this?

Todd

**Comment by toddapetersen** [comment]
Here are some additional thoughts.     At 15 mph, scooters will travel 22 ft / sec.   An interval of 5 seconds results in 110 ft resolution.   An LA City block is about 500 ft long.    

Given this, I would recommend an interval not to exceed `6 seconds` so we can get 1/4 block resolution.   This makes it useful for planning of future bike lanes, etc.

**Comment by hunterowens** [comment]
Provider side mention all possible points. If we find issue with this, I would recommend that we could consider minimum device standards in future regs.
