### ISSUE TITLE
Agency: Service Areas

### ISSUE THREAD

**Issue by geobir** [CityOfLosAngeles/mobility-data-specification#334]
### Is your feature request related to a problem? Please describe.

The [Type](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/agency#area-types) of [Agency, Service Areas](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/agency#service-areas) are missing enums.

### Describe the solution you'd like

We may want to __split restricted pick-up and drop-off__.
Also, in Europe, and all around the world some city's ask for __speed limit area__ (maximum and/or minimum), I would like to add this new type of areas.

### Is this a breaking change

If we add new enums (restricted_pick_up, restricted_drop_off, max_speed, min_speed for example) it's not a breaking change.
We will have to add numbers for max_speed and min_speed enum.

 * No, not breaking

### `Provider` or `agency`

For which API is this feature being requested:
 * `agency`

### Additional context

You can also see #259 who also speak about 'service_area'

> The Mayor of Paris has just announced a complete sidewalk ban on electric scooters, which includes both riding and parking. The electric scooters can now only be parked in designated parking spots for cars or motorcycles/mopeds.
> 
> In addition, the Mayor has asked electric scooter companies to limit their speeds to 20 km/h (12 mph) across the city and down to just 8 km/h (5 mph) in areas with high pedestrian traffic.

**Comment by karcass** [comment]
`/service_areas` are frozen and will be deprecated post 0.4.0.  Ideas like preferred-pick-up and cap-counts and such will be expressed via the Policy API.  Please check out that API in its PR (#322).  The prototype of the code is in the CityOfLosAngeles `mds-core` repo.

**Comment by geobir** [comment]
@karcass Thank you, I close this issue and I will follow the #322.
