### ISSUE TITLE
Why does the provider has to call service areas?

### ISSUE THREAD

**Issue by patata3000** [CityOfLosAngeles/mobility-data-specification#346]
I'm asking this because if the city wants to be able to give some updates about the Service Areas (eg: in case of public event (concert)), it has to wait for the provider to call `/service_areas`.
You could just have an agreement with the provider to call `/service_areas` endpoint every 5min to avoid having to wait too long for the him to make the call or you could add an endpoint `service_areas` in the provider API so the agency can push data as soon as they can.

I'm rooting for the second option.

My uncertainty on this subject is that I'm not sure that `/service_areas` exists for these kind of problems.

**Comment by karcass** [comment]
`/service_areas` is slated for deprecation in favor of the new Policy spec.  Until that happens, yes, polling is the correct answer.  It is up to the agency to specify how often the providers should poll `/service_areas` for changes.

**Comment by karcass** [comment]
I agree, frequent polling is not a preferred method for communication. Adding an endpoint to Provider to indicate an update to `/service_areas` or Policy objects is one possible approach, but alternatives include websockets, long-polling, and SSE. As MDS evolves we might add these other communication methods.

**Comment by karcass** [comment]
Hi @patata3000.  If you are satisfied, please close this ticket.
