### ISSUE TITLE
Field size limitation

### ISSUE THREAD

**Issue by patata3000** [CityOfLosAngeles/mobility-data-specification#348]
Is there a plan to add a field size limitation. For example, the device_id or vehicle_id could be limited in their number of characters.

**Comment by karcass** [comment]
`device_id` is a UUID, so it has fixed length.

`vehicle_id` should probably have a maximum length.  The reference implementation uses a `varchar(32)`, and so far that hasn't been a problem in practice.

**Comment by karcass** [comment]
It probably wouldn't harm anything to bump that to, say, 256 characters, and call it done.

**Comment by hunterowens** [comment]
yeah, I mean, theoretically vehicle_id needs to be printed on the vehicle. I suppose we should have this all done inside the JSONschema.

**Comment by karcass** [comment]
We bumped the implementation of Agency varchar items to 255.  I'll add a PR for that.

**Comment by hunterowens** [comment]
fixed! #361
