### ISSUE TITLE
Remove vehicle_id and device_id params from Trips endpoint 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mobility-data-specification#350]
### Is your feature request related to a problem? Please describe.

On the [2019.08.08 call](https://github.com/CityOfLosAngeles/mobility-data-specification/wiki/Web-conference-notes,-2019.08.08), it turns out nobody is using the vehicle_id and device_id query params and it is essentially limited to the time params. Removing this will allow caching to be more easily implemented and enable a solution to #268 

### Describe the solution you'd like

Remove unused query params 
### Is this a breaking change

 * Yes, breaking

### `Provider` or `agency`

For which API is this feature being requested:

 * `provider`

**Comment by babldev** [comment]
+1 Thanks!
