### ISSUE TITLE
Improved release meeting communications

### ISSUE THREAD

**Issue by sarob** [CityOfLosAngeles/mobility-data-specification#364]
### Is your feature request related to a problem? Please describe.

Not so much a feature rather an project dev process change. 

### Describe the solution you'd like

Only publishing meeting details and agenda by mailing list makes it harder to follow and track what is happening next. I propose instead creating the wiki meeting page before the meeting along with the ways to join the meeting and the agenda. This also has the added benefit that others could propose agenda items as well. [I have created a wiki page template to start the conversation.]( https://github.com/CityOfLosAngeles/mobility-data-specification/wiki/Web-Conference-Template) 

### Is this a breaking change

 * No, not breaking

### `Provider` or `agency`

For which API is this feature being requested:

 * None 

### Describe alternatives you've considered

* None

### Additional context

I have used similar method for other projects using wiki pages and gdocs. It seems to work well.

**Comment by hunterowens** [comment]
This is great @sarob. Can you add this documentation to the `releaseGuidelines.md` document?

**Comment by sarob** [comment]
Glad you like the idea. I will modify ReleaseGuldelines.md As per https://github.com/CityOfLosAngeles/mobility-data-specification/issues/364


~ sean

**Comment by sarob** [comment]
I am looking for the google calendar MDS release meeting URL. 
Please share here.
