### ISSUE TITLE
Discussion: create a central registry of Providers?

### ISSUE THREAD

**Issue by thekaveman** [CityOfLosAngeles/mobility-data-specification#39]
Similarly to how GBFS maintains a central [`systems.csv`](https://github.com/NABSA/gbfs/blob/master/systems.csv) file, should MDS maintain a `providers.csv` (or similar)?

MDS regulators (*municipalities*) need a way to uniquely identify each of the different `provider` data feeds. On the other hand, a given `provider` may have a different MDS feed for many different municipalities.

Rather than forcing each `provider` to register with each municipality separately (to obtain a unique `provider_id`), the idea is to maintain a single, central source of truth. 

An example schema:

| provider_id | provider_name | url |
| ------------------|-------------|-------|
| MDS-wide unique provider identifier | human friendly company name | Company website URL |

Does it make sense to have the `provider` API URL as part of this registry? If that is the case, the API needs to support queries for a particular municipality (e.g. by geo-fenced area).

**Comment by hunterowens** [comment]
I think this would be great to have. 

Ideally, we could have folks on the 12th make a PR for inclusion. @toddapetersen @thecorconian @black-tea thoughts?

**Comment by hunterowens** [comment]
Actually, let's have  a few providers add initial registries to this thread and we can incorporate

**Comment by hunterowens** [comment]
Another though: We should probably capture the MDS base url - ie, something like `mds.api.my-company.co`

**Comment by thekaveman** [comment]
@hunterowens I was wrestling with including that field as well, but ultimately I agree.

Also, agreed that we should get some providers to weigh in here. Leaving it open for discussion and will hold off on any file additions until then.

**Comment by c-fang** [comment]
@thekaveman @hunterowens Representative here from a provider. A providers.csv file as described sounds good to us, will follow up offline to agree on the provider ID
