### ISSUE TITLE
Add Provider Baus

### ISSUE THREAD

**Issue by tomsant** [CityOfLosAngeles/mobility-data-specification#394]
### Is your feature request related to a problem? Please describe.

Operator Baus needs to be added to providers.csv

### Describe the solution you'd like

Add row for Baus with values below:

provider_name: Baus
provider_id: {provided by hunter?}
url: https://bausmoves.com
mds_api_url: https://mds.bird.co
gbfs_api_url: https://mds.bird.co/gbfs/gbfs/platform-partner/v2/baus

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

 * Yes, breaking
 X No, not breaking
 * I'm not sure

### `Provider` or `agency`

For which API is this feature being requested:

X `provider`
 * `agency`
 * both

### Additional context

New Bird Platform Partner - Baus.

**Comment by hunterowens** [comment]
@tomsant: Thanks! 

Feel free to open a PR with this info, the provider_id is generally self submitted. To generate a uuid in python, for example, run 

```python 
import uuid 
uuid.uuid4()
```

**Comment by tomsant** [comment]
Thanks @hunterowens !  I opened the PR.
