### ISSUE TITLE
Consider using JSON Schema

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/mobility-data-specification#46]
The mobility spec already provides some nice narrative description of the inputs and outputs for the REST API. However, there is still some room for ambiguity, and it would be useful to be able to test providers/agencies against regressions and compliance with the spec.

One commonly-used approach to this problem is to use a [JSON schema](https://json-schema.org). This allows you to describe JSON data structures in a well-typed fashion. This allows for
* validation
* regression testing
* a source of truth for the spec to guard against different interpretations of the narrative.
* Easier tracking of spec versions

For instance, a schema for the response body of the `/deregister-vehicle` might look something like:
```json
{
  "properties": {
    "unique_id": {
      "type": "string"
    },
    "device_id": {
      "type": "string"
    },
    "reason_code": {
      "type": "string",
      "enum": ["rebalancing", "maintenance"]
    }
  },
  "type": "object",
  "additionalProperties": false
}
```
High-quality JSON-schema validators should exist in most web-friendly languages.

**Comment by thekaveman** [comment]
I think this is a great idea.

I will start putting together a PR for `provider` using JSON-schema so we can explore this idea further.

**Comment by thekaveman** [comment]
I started putting something together over here: https://github.com/CityofSantaMonica/mobility-data-specification/blob/json-schema/provider/schema.json

Take a look at let me know if this seems like the right direction. I generated this using some sample data I cooked up and the tool at https://www.jsonschema.net/

**Comment by ian-r-rose** [comment]
@thekaveman that's awesome. Can you open a PR to allow for commenting?

**Comment by hunterowens** [comment]
This would be a breaking change, tagging as a 0.2.0 milestone.

**Comment by hunterowens** [comment]
#53 is merged. closing.
