### ISSUE TITLE
Lime Comments

### ISSUE THREAD

**Issue by samlimebike** [CityOfLosAngeles/mobility-data-specification#6]
**Data Sharing Comments**

1. Definition of real-time: in numerous places in the document you reference real-time. This is not well-defined.
- Recommendation:  Use real time defined as "in as real time as possible", with the understanding that it may be minutes old and not at that very second.

2. Trip Data Query Parameters: It is quite complex to have the API be queryable and this is not currently the industry practice.
- Recommendation: To avoid system issues, the API should directly return /trips without the query parameters with a reasonable maximum number of records that can be returned (e.g. up to 1-day, or a few days)

3. Service area metrics: Similar to #2 above, it’s quite complex to allow querying by GeoJSON.
- Recommendation: It should be queried by service area ID.

4. Movement Plans: These appear to be specific to rideshare and would not be relevant to our industry.
- Recommendation: Remove this API requirement

5. Maintenance Reporting: This is not industry practice to convert maintenance records into API format.
- Recommendation: Operator should submit summary reports of maintenance tickets.

6. System Data / Availability Data: These are not clearly defined; for example, the difference between placement_reason and pickup_reason isn’t clear. Definitions should be more specific.
- Recommendation: Operators should provide the counts of available vehicles or list of unique IDs of vehicles that are available at time of query.  We propose the use of the format we authored here for vehicle availability: https://bitbucket.org/limebike/dbfs/src/15d8a74b10ee1a0c5109d3c14bfd03cce02ece46/dbfs.md?at=master&fileviewer=file-view-default#get-bikes 

7. Update-trip-data: We cannot guarantee this service level as the requested frequency granularity is very high. 
- Recommendation: Focus on submitting a single record for each trip instead. 

**Fleet Size Comments**

1. Maximum fleet size: We recognize the addition in the staff report permitting operators to add 2,500 vehicles in disadvantaged communities. Nonetheless, enforcing a cap on operators does not permit operators to scale based on demand nor does it incentivize high quality service.
- Recommendation: Institute an expansion plan of 1,000 vehicles per month as a baseline that operators can qualify for by being part of the pilot program. Operators should then be able to apply for expansion beyond this 1,000 vehicles/month based on several criteria, such as: meeting a threshold of 2 trips/bike/day for bicycles and electric-assist bicycles and 3 trips/scooter/day for electric scooters; meeting operational performance criteria including customer service response time; and meeting community engagement targets.

**Parking Requirements**

1. Locking mechanism requirement: Requiring every vehicle to have a locking mechanism to lock to a fixed object raises equity questions as not every community has proper bike parking infrastructure, while also posing potential obstacles from bikes locked to ADA rails, construction equipment, or other non-bike parking objects.
- Recommendation: Operators should be encouraged to add lock-to on their vehicles but not required.

**Geofencing Comments**

1. Geo-fencing requirement around Metro Bike Share and Downtown: Forcing operations to take place outside of areas near existing Metro Bike Share stations or the downtown area severely impacts our ability to serve the community on multiple levels. First, these are areas where traffic congestion and parking are the most severe. Also, solving first-last mile gaps becomes near impossible if riders cannot ride to a rail station or bus station where there is also a Metro Bike Share station; communites that live within 3 miles of a Metro Bike Share station but do not have a station nearby are also not able to enjoy dockless mobility, posing an equity challenge. As Metro Bike Share expands, this requirement will also make it near impossible to serve the City of Los Angeles in a meaningful way. In addition, there is no clear reason for why "dockless bike share shall not be allowed to directly compete with Metro Bike Share at this time" - dockless bike share systems have operated alongside dock-based bike share systems in other cities and have not been negatively impacted by it (see Washington, D.C.'s Capital Bikeshare system's record ridership during the same time dockless mobility companies have been in operation).
- Recommendation: Remove the geofence restriction to allow for equitable service of the City

**Equity Comments**

1. Low-income plan requirement: LADOT should better define how operators can qualify individuals as low-income and have the low-income plan match other low-income transportation discounts, rather than forcing free rides under 30 minutes.
- Recommendation: Define low-income plan qualifiers as an individual who qualifies for state or local low-income plan with the plan being a heavily discounted fare equivalent to current low-income transportation discounted fares.

**Comment by hunterowens** [comment]
Hi @samlimebike: 2 quick things

1) the link to bitbucket is currently password protected. 

2) can you please open each section (ie, `equity` or `geofencing`) of this document as an individual issue. We will respond in those issues.
