### ISSUE TITLE
Have the trip_id be generated by the provider not the agency 

### ISSUE THREAD

**Issue by aickin** [CityOfLosAngeles/mobility-data-specification#63]
In the current spec, `trip_id` is generated by the agency in response to a `start_trip` call. I think this creates an undesirable dependency on the agency’s infrastructure. 

If I’m reading correctly, the `trip_id` is also used in `end_trip` and `trips` APIs. Now, imagine that the agency’s API server goes down for whatever reason (bugs, power outage, network outage, server maintenance, etc.). The provider will attempt to call `start_trip` and get a failure. Now they don’t have a trip ID with which to identify the trip, so they are in a pickle. If they go ahead and start the trip, it will never have an agency-approved trip ID. If they don’t start the trip, their service is effectively shut down. 

I would suggest moving `trip_id` to be an argument to `start_trip` rather than a return value. This would eliminate the dependency. 

Thanks for all the good work!

**Comment by ezheidtmann** [comment]
Yep -- this is also key to avoid duplicates in a number of failure scenarios.

**Comment by migurski** [comment]
Trip IDs should be generated differently in the Provider and Agency APIs, so they might not be equivalent concepts. UUID4 offers a way to ensure that these are mutually globally unique, but for each API the hosting organization (vendor or city) should be responsible for generating its own internal primary keys.

**Comment by oderby** [comment]
This seems to have been resolved in #194. @hunterowens I think we can close?

**Comment by toddapetersen** [comment]
Agreed with @oderby.  Resolved in current Agency version.
