### ISSUE TITLE
device_id for scooters without GPS

### ISSUE THREAD

**Issue by asadowns** [CityOfLosAngeles/mobility-data-specification#69]
We have scooters in our fleet that do not have their own GPS but piggyback off the user's bluetooth.

For these devices we do have a unique identifier for the scooter but it is not tied to the unit that transmits GPS. 

In these cases how should we handle device_id?

Relevant spec
> MDS defines the device as the unit that transmits GPS signals for a particular vehicle. A given device must have a UUID (device_id below) that is unique within the Provider's fleet.
> Additionally, device_id must remain constant for the device's lifetime of service, regardless of the vehicle components that house the device.

**Comment by hunterowens** [comment]
In this case I think best practice should be that each scooter has device_id. I think we might want to change the spec in this case.

**Comment by asadowns** [comment]
Sounds good. We will proceed in this direction. Let me know if you want me to update the spec

**Comment by hunterowens** [comment]
Pull request on this welcome to clarify if needed, but given that it seems like most folks are moving away from that type of device, I think we might be able to just to refer to this issue if more questions come up. Closing for now.
