### ISSUE TITLE
Clarify `event_location` type in status changes

### ISSUE THREAD

**Issue by ezheidtmann** [CityOfLosAngeles/mobility-data-specification#74]
Should the location be a `Point` geometry or a route point feature with `horizontalAccuracy`?

https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/provider/README.md#status-changes

**Comment by thekaveman** [comment]
I think we've decided on `Feature` to allow additional properties such as `horizontalAccuracy`. PR's welcome!
