### ISSUE TITLE
Trip Data Privacy Concerns

### ISSUE THREAD

**Issue by noonhub** [CityOfLosAngeles/mobility-data-specification#75]
First, I want to say that JUMP’s goal is to promote the safety of our riders while partnering with cities to provide access to the data required for city-planning.  As noted during the workshop, sharing raw location data in the form of start and stop locations, route data and/or trip history presents a risk of re-identification that may endanger the privacy of our users.  

Below, I have outlined a few approaches to lessening the privacy impact related to  trip data, some of which have already been mentioned in issues #68, #66 & #61.  JUMP would appreciate the opportunity to discuss any of these approaches in more detail with LADOT staff.

### Trip Data Obfuscation Methods

* Limit location & time accuracy:  limiting GPS precision based on population density of a particular city in combination with time aggregation is one means of anonymizing data.  Depending on LA’s population density and trip count, providing GPS with two or three decimal places and on an hourly time aggregation may be a acceptable solution.  One way to implement this within the MDS is to add an “accuracy” field in the collection of all timestamp and location data.

* Snap to nearest census block: operators can systematically fuzz the start and stop locations by “snapping” location data to the center of the nearest census block or predefined area.  To maintain privacy, route location data should also be anonymized across location and time. 
  
* Aggregate route data:  operators may provide specific route data only once a minimum number of trips using that route occured in a specific time period.  For example, route data would be provided for a trip from point A to point B only when at least 30 similar trips occured in a given time period.  Start and stop locations could also be anonymized by either “snapping” or limiting GPS accuracy. 

### GBFS Feed - Real Time Availability 

As designed, the GBFS feed does not adequately protect the privacy of its users.  While the bikes “on trip” are not shown, anyone with access to the system can easily reconstruct a trip by tracking when bikes are reserved (at which time they disappear from the map) and when the reservation ends (when they reappear). This information can be used to build a database of historic trip information and ultimately re-identify users based on their trip history.  One fix for this problem is to scramble the bike identifiers during a trip so it is impossible to determine which start and stops constitute a unique trip. 

### User Consent   

Operators may offer users the choice to share trip  data with cities without anonymization via opt-in.  This could be in addition to a truly anonymized method above, which would not be subject to consent.

**Comment by LADOTBikeshare** [comment]
LADOT has reviewed the comment and we have include our a link to the guidelines for handling the data in the README. ref #154
