### ISSUE TITLE
Some ideas on the specs

### ISSUE THREAD

**Issue by monolyst** [CityOfLosAngeles/mobility-data-specification#8]
Not an issue- just a few quick thoughts from SDOT.

Trip Data
route: could this specify an encoded polyline algorithm such as https://developers.google.com/maps/documentation/utilities/polylinealgorithm?
 
trip_duration: could this be calculated?
 
trip_distance: is this distance calculated or the actual route distance? 
 
start_point/end_point: we will be geocoding to blockgroup. Would the companies be able to geocode this on their end, or can the API geocode this automatically? 
 
start_time, end_time: we use unix timestamp a lot. Sometimes  I prefer ISO 8601 because it’s human readable and doesn't require conversion. We usually screw up daylight savings time.
 
System Data / Availability: would we need to specify geography or time period granularity? 
 
Realtime Data: The feed might be an easier way to measure availability. It might be good to specify which fields are required. I think these should be point coordinates, device_type, device_id.  We would need to know status (rented or available). If there is no status, the feed should only return available bikes.

**Comment by hunterowens** [comment]
@monolyst sorry for the long, long delay, but I'd encourage you to take a look at the current version as written. 

Availability is calculated via SQL view for us. The code for that lives in the mds-dev repo. 

Hope you can join us on the call / meeting next week.
