### ISSUE TITLE
start/end time clarification

### ISSUE THREAD

**Issue by noonhub** [CityOfLosAngeles/mobility-data-specification#83]
I would like to clarify exactly what `start_time` and `end_time` mean for `GET /trips`

Does this refer to when the rider created a booking on the platform or when the route actually starts? What should the trip object look like for a canceled booking or a trip that otherwise didn't "start"?

**Comment by thekaveman** [comment]
Good questions. I'm going to close this as duplicates of #55 and the related PR #52. Let's move discussion to those open tickets, thank you!
