### ISSUE TITLE
Unix Timestamp clarification in Provider API

### ISSUE THREAD

**Issue by asadowns** [CityOfLosAngeles/mobility-data-specification#87]
Time fields like `start_time`, `end_time`, and route `timestamp` currently specify their type as `Unix Timestamp`. An example from route `timestamp` is `1531007628.3774529`. 

This leaves it open to interpretation and confusion what the correct format is. 

GBFS spec specifies for instance
> Integer POSIX timestamp

and provides an example `1434054678` or epoch seconds.

So using the example from route it should be either `1531007628` for epoch seconds. Or, if greater precision is required epoch milliseconds would be `531007628377`.

In either case it would be good to clarify what the preferred format for providing time is. If you let me know your preference, I'll put out a PR.

**Comment by thekaveman** [comment]
Great point @asadowns, some clarification would be useful here. I personally like the GBFS approach; keeping it as integer, epoch seconds. I can't think of why millisecond precision would be necessary for `provider`. Yet on the `agency` side, I can see where that might matter more.

And ideally, as elsewhere, the two should be aligned where possible.
