### ISSUE TITLE
Consider multiple stops within a route, perhaps calling this a `trip`?

### ISSUE THREAD

**Issue by rlucas7** [CityOfLosAngeles/mobility-data-specification#89]
The current spec defines a route as a start and a stop point. Some trips may go from points A, C via an intermediary point B. For example, tourists in Manhattan might get a bike rental and go from A to B, doc the bike (b/c of time limitations) and then take the bike back out immediately. With the current spec you I don't think you could include this into the json.

**Comment by thekaveman** [comment]
> The current spec defines a route as a start and a stop point.

I think you may be misinterpreting the wording of the spec, and/or the wording could use clarification, and/or I am misinterpreting the issue you bring up. Under the [route details](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/master/provider#routes) it states:

>> MDS provider APIs should create a GeoJSON Feature Collection, which includes every observed point in the route [...] Routes must include at least 2 points: the start point and end point

So the route *minimally* includes the start and end point. 

> Some trips may go from points A, C via an intermediary point B. For example, tourists in Manhattan might get a bike rental and go from A to B, doc the bike (b/c of time limitations) and then take the bike back out immediately.

For this scenario, MDS would consider each leg a distinct Trip (each with its own `route` and associated details), with at least 4 distinct Status Changes (`start: A -> B`, `end: A -> B`, `start: B -> C`, `end: B -> C`)

**Comment by rlucas7** [comment]
@thekaveman, I missed the `at least` part! Thanks for point out, that changes things a bit. I live in Manhattan and I'd guess there are *many* ways to get from `A->B` so I was thinking about how one might visualize these trips. Having intermediate points is useful to infer some specificity in the path. Not sure if that use case is of interest or not though. I'll close the issue.
