### ISSUE TITLE
Lock-to

### ISSUE THREAD

**Issue by sleibman** [CityOfLosAngeles/mobility-data-specification#9]
We request that LADOT remain firm on its commitment to locking mechanisms on dockless vehicles to prevent dockless bikes and scooters from blocking sidewalks for pedestrians, the elderly, and those with disabilities by removing the following sentence from Parking Rule B: 

> "However, locking mechanism requirement may be waived at LADOT discretion." 

An alternative would be to require dockless operators to either have a lock-to mechanism, or to require dockless operators to include a notification mechanism in their app that reliably notifies users that their vehicle is properly parked upright in a geo-fenced, designated area by the city (similar to rules approved by the city of Austin).

**Comment by LADOTBikeshare** [comment]
Thank you for your comment. LADOT has taken this comment into consideration and has closed this issue.
