### ISSUE TITLE
Add Provider ID: SFMTA Commuter Shuttle Operators

### ISSUE THREAD

**Issue by matthewmarwedel** [CityOfLosAngeles/mobility-data-specification#920]
**Note:** See the [Adding an MDS Provider ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) page for more help.

Opening this issue will allow you as a mobility service provider or data source provider to get an official provider ID for use across MDS globally.

**Fields needed from you for the [providers.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/providers.csv).**

_All fields are required._

Hi! SFMTA (San Francisco Municipal Transportation Agency) is adding their commuter shuttle data to MDS so we would like to add all of our shuttle operators and shuttle data providers to the MDS provider list. I will provide the information for the all 16 providers we would like to add in this issue request. I am using `passenger-services` as the mode_id, however, if OMF would like to add a new option for `commuter-shuttle` or `bus` we would be fine with that too.

I am leaving the mds_api_url as null as the shuttle/data company listed will send this information to OMF separately at a later date.

Also we have a gtfs (General Transit Feed Specification) api_url that can be provided instead of the gbfs_api_url, would you like to create a new column for the gtfs_api_url? Please let us know.

1. **provider_name** - Short name of your company.
   - Bauer's Intelligent Transportation
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 46454118-168c-40e1-93bb-53e68e3f03bf
1. **url** - URL to the home page of your company.
   - https://bauersit.com
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - MV Transportation
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - e4722796-4e0e-4203-8ae9-546bdcc4aa52
1. **url** - URL to the home page of your company.
   - https://www.missionbaytma.org/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - CLS Global Transportation
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 64477ac9-0c53-4031-98a4-ffe83bd94590
1. **url** - URL to the home page of your company.
   - https://clsgt.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Compass Transportation
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - f00500e6-55b9-4cdf-afe9-68db2822a3e2
1. **url** - URL to the home page of your company.
   - https://www.compasstransportation.net/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Corinthian International
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 0666cc3c-a346-4413-aa16-241c48281afb
1. **url** - URL to the home page of your company.
   - http://corinthianparking.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Hallcon
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - d6354b9d-4179-465f-b663-648a6fc054a5
1. **url** - URL to the home page of your company.
   - https://hallcon.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Kaiser Permanente
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 5e96f9c3-bd41-4337-a436-475fc9747621
1. **url** - URL to the home page of your company.
   - https://kp.org/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Lux Bus America
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 0697d1bb-1678-4375-b8c6-9e09e363cbfa
1. **url** - URL to the home page of your company.
   - https://luxbusamerica.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Lux Leasing
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - fe7a26bc-a0bb-4943-b335-cd334d4f5fab
1. **url** - URL to the home page of your company.
   - https://luxbusamerica.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Royal Coach Tours
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 095da27f-7bbd-45f1-b00b-eb52b244ccd4
1. **url** - URL to the home page of your company.
   - http://royal-coach.com
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Storer
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - eee92c25-89f5-4e03-a4c7-b6dac883732a
1. **url** - URL to the home page of your company.
   - https://storercoachways.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - We Drive U Inc
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 5488c6d1-baa8-4994-8763-a2c48090631a
1. **url** - URL to the home page of your company.
   - https://wedriveu.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Samsara
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - aa055687-5947-4921-ae1d-70d7755609ae
1. **url** - URL to the home page of your company.
   - https://samsara.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Tripshot
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - e154cf80-df89-4d7e-b5e7-2ee8050a6e9c
1. **url** - URL to the home page of your company.
   - https://www.tripshot.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Trakk
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 6a907d9d-1e3c-4cb6-991c-f9738d30337b
1. **url** - URL to the home page of your company.
   - https://gettrakk.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
1. **provider_name** - Short name of your company.
   - Swoop
1. **mode_id** - The mode that you support. Use the mode short identifier from `micromobility`, `passenger-services`, `delivery-robots`, `car-share`. Register a unique ID for each mode you support.
   - passenger-services
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 08ad2b21-8115-4d18-874f-48082e8e50fb
1. **url** - URL to the home page of your company.
   - https://www.swoopapp.com/
1. **mds_api_url** - Full https:// base URL where your root MDS feeds are located.
   - null
1. **gbfs_api_url** - Full https:// base URL where your public GBFS feeds are located.
   - null
 ---
Additionally, please provide your name and role within your agency to help with verification.
   - Matt Marwedel, Data Consultant at SFMTA

**Comment by alexdemisch** [comment]
One overarching question to consider as we try to adapt MDS for our [Commuter Shuttle Program](https://www.sfmta.com/projects/commuter-shuttle-program) is whether it can be part of passenger services or if it needs a new mode.  These are all fixed route services.

**Comment by schnuerle** [comment]
We'll be talking about this to tomorrow's [MDS WG meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2024.10.24-(MDS-Working-Group)). Regardless of the outcome of the solution to #922, these new operators can be added to the provider list.

**Comment by monachiu** [comment]
If this request was added to the 2.1.0 milestone, when will these providers ID be add to the provider list and can use?

**Comment by schnuerle** [comment]
Complete with #921.

These IDs can be used now. If you need to point to something official, point to the `dev` branch [here](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv). They will go to the `main` branch when 2.1 is approved. 

Note please come back and add the MDS root URLs when you have them later.
